## Purpose

This notebook will serve as an aggregation notebook, bringing in the data, joining the data on different fields, and creating an aggregation data frame that can be used for further analysis

In [1]:
import pandas as pd

In [3]:
# Bring in data 
country_codes = pd.read_csv('country_codes.csv')
famine_ships = pd.read_csv('famine_Irish_Ships.csv')
job_codes = pd.read_csv('jobs_codes.csv')
port_codes = pd.read_csv('port_codes.csv')

In [2]:
fipas = pd.read_csv('fipas.csv')

fipas.head()

/var/folders/h6/yxy6glj14rd2c83llgj50xnc0000gn/T/ipykernel_75318/235920302.py:1: DtypeWarning: Columns (2,5,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  fipas = pd.read_csv('fipas.csv')

,last_name,first_name,age,sex,occupation_code,literacy code,native_country,last_residence,destination,transit_code,travel_compartment,port_of_embark,arrival_month,arrival_date,arrival_year
0,SOMER,JOHN,17,M,TLR,U,117.0,U,USA,S,13,769,1,12,1846
1,LOCKE,ELLEN,44,F,WVR,U,3.0,U,USA,S,13,771,1,15,1846
2,LOCKE,CATHERINE,22,F,WVR,U,3.0,U,USA,S,13,771,1,15,1846
3,SHERIDAN,MARY,18,F,WVR,U,3.0,U,USA,S,13,771,1,15,1846
4,MCNAMEE,ARTHUR,20,M,LABR,U,3.0,U,USA,S,13,771,1,15,1846

In [4]:
job_codes.head()

     job_name job_code
0  ACCOUNTANT     ACCT
1       ACTOR       AR
2     ACTUARY      ATR
3    ADJUSTER      ADJ
4  ADVENTURER   ADVNTR

In [7]:
# Merge fipas with job_codes
# Create new df 'agg_data'
agg_data = pd.merge(fipas, job_codes, how='left',
                    left_on='occupation_code',
                    right_on='job_code')

print(agg_data.head())

  last_name first_name age sex occupation_code literacy code  native_country  \
0     SOMER       JOHN  17   M             TLR             U           117.0
1     LOCKE      ELLEN  44   F             WVR             U             3.0
2     LOCKE      ELLEN  44   F             WVR             U             3.0
3     LOCKE  CATHERINE  22   F             WVR             U             3.0
4     LOCKE  CATHERINE  22   F             WVR             U             3.0

  last_residence destination transit_code travel_compartment  port_of_embark  \
0              U         USA            S                 13             769
1              U         USA            S                 13             771
2              U         USA            S                 13             771
3              U         USA            S                 13             771
4              U         USA            S                 13             771

   arrival_month  arrival_date  arrival_year          job_name job_code
0              1            12          1846  TAILOR/TAILORESS      TLR
1              1            15          1846         TESSITORE      WVR
2              1            15          1846  WEAVER/TESSITORE      WVR
3              1            15          1846         TESSITORE      WVR
4              1            15          1846  WEAVER/TESSITORE      WVR

In [15]:
print(country_codes.tail(10))

    country_code                 country
23            61                  BRAZIL
24            72               ST. CROIX
25            93                 UNKNOWN
26            99                 UNKNOWN
27           117           GREAT BRITAIN
28           126            NEWFOUNDLAND
29           141               FRANKFURT
30           150  JERSEY, CHANNEL ISLAND
31           151                 MOROCCO
32           152    PRINCE EDWARD ISLAND

In [11]:
# Change country_code column to integer
agg_data['native_country'] = agg_data['native_country'].apply(lambda x: int(x) if pd.notnull(x) else x)
print(agg_data.head())

  last_name first_name age sex occupation_code literacy code  native_country  \
0     SOMER       JOHN  17   M             TLR             U           117.0
1     LOCKE      ELLEN  44   F             WVR             U             3.0
2     LOCKE      ELLEN  44   F             WVR             U             3.0
3     LOCKE  CATHERINE  22   F             WVR             U             3.0
4     LOCKE  CATHERINE  22   F             WVR             U             3.0

  last_residence destination transit_code travel_compartment  port_of_embark  \
0              U         USA            S                 13             769
1              U         USA            S                 13             771
2              U         USA            S                 13             771
3              U         USA            S                 13             771
4              U         USA            S                 13             771

   arrival_month  arrival_date  arrival_year          job_name job_code
0              1            12          1846  TAILOR/TAILORESS      TLR
1              1            15          1846         TESSITORE      WVR
2              1            15          1846  WEAVER/TESSITORE      WVR
3              1            15          1846         TESSITORE      WVR
4              1            15          1846  WEAVER/TESSITORE      WVR

In [17]:
null_count=agg_data['native_country'].isnull().sum()
print(null_count)

0

In [16]:
# Replace nulls with '99'
agg_data['native_country'] = agg_data['native_country'].fillna(99)

In [18]:
# Confirm that native_country values are int
agg_data['native_country'] = agg_data['native_country'].astype(int)

In [19]:
# Confirm that country_code in country_codes is int
country_codes['country_code'] = country_codes['country_code'].astype(int)

In [20]:
# Merge agg_data with country_codes
agg_data = pd.merge(agg_data, country_codes, how='left',
                    left_on='native_country',
                    right_on='country_code')

print(agg_data)

       last_name first_name age sex occupation_code literacy code  \
0          SOMER       JOHN  17   M             TLR             U
1          LOCKE      ELLEN  44   F             WVR             U
2          LOCKE      ELLEN  44   F             WVR             U
3          LOCKE  CATHERINE  22   F             WVR             U
4          LOCKE  CATHERINE  22   F             WVR             U
...          ...        ...  ..  ..             ...           ...
759321     SMITH         ED  21   M            GENT             3
759322     SMITH        ANN  18   F             LDY             3
759323    LESTIN     U-MRS.  28   F               U             3
759324    LESTIN       MARY   2   F              CH             3
759325   LOUGHAN       MARY   4   F              CH             3

        native_country last_residence destination transit_code  \
0                  117              U         USA            S
1                    3              U         USA            S
2                    3              U         USA            S
3                    3              U         USA            S
4                    3              U         USA            S
...                ...            ...         ...          ...
759321              99              U         USA          NaN
759322              99              U         USA          NaN
759323              99              U         USA          NaN
759324              99              U         USA          NaN
759325              99              U         USA          NaN

       travel_compartment  port_of_embark  arrival_month  arrival_date  \
0                      13             769              1            12
1                      13             771              1            15
2                      13             771              1            15
3                      13             771              1            15
4                      13             771              1            15
...                   ...             ...            ...           ...
759321                NaN            5724             12            31
759322                NaN            5724             12            31
759323                NaN            5724             12            31
759324                NaN            5724             12            31
759325                NaN            5724             12            31

        arrival_year          job_name job_code  country_code        country
0               1846  TAILOR/TAILORESS      TLR         117.0  GREAT BRITAIN
1               1846         TESSITORE      WVR           3.0        IRELAND
2               1846  WEAVER/TESSITORE      WVR           3.0        IRELAND
3               1846         TESSITORE      WVR           3.0        IRELAND
4               1846  WEAVER/TESSITORE      WVR           3.0        IRELAND
...              ...               ...      ...           ...            ...
759321          1851         GENTLEMAN     GENT          99.0        UNKNOWN
759322          1851              LADY      LDY          99.0        UNKNOWN
759323          1851               NaN      NaN          99.0        UNKNOWN
759324          1851               NaN      NaN          99.0        UNKNOWN
759325          1851               NaN      NaN          99.0        UNKNOWN

[759326 rows x 19 columns]

In [21]:
agg_data.head()

,last_name,first_name,age,sex,occupation_code,literacy code,native_country,last_residence,destination,transit_code,travel_compartment,port_of_embark,arrival_month,arrival_date,arrival_year,job_name,job_code,country_code,country
0,SOMER,JOHN,17,M,TLR,U,117,U,USA,S,13,769,1,12,1846,TAILOR/TAILORESS,TLR,117.0,GREAT BRITAIN
1,LOCKE,ELLEN,44,F,WVR,U,3,U,USA,S,13,771,1,15,1846,TESSITORE,WVR,3.0,IRELAND
2,LOCKE,ELLEN,44,F,WVR,U,3,U,USA,S,13,771,1,15,1846,WEAVER/TESSITORE,WVR,3.0,IRELAND
3,LOCKE,CATHERINE,22,F,WVR,U,3,U,USA,S,13,771,1,15,1846,TESSITORE,WVR,3.0,IRELAND
4,LOCKE,CATHERINE,22,F,WVR,U,3,U,USA,S,13,771,1,15,1846,WEAVER/TESSITORE,WVR,3.0,IRELAND

In [ ]:
# Examine famine Irish Ships